name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
          check-latest: true
          cache: true
      - name: test-coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test
          coverageLocations: ${{ github.workspace }}/coverage.out:gocov
          prefix: github.com/${{ github.repository }}
  codeql:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
          check-latest: true
          cache: true
      - name: init codeql
        uses: github/codeql-action/init@v2
        with:
          languages: 'go'
      - name: run analysis
        uses: github/codeql-action/analyze@v2
